/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package P1;

import static P1.Mattel.Escritura_Txt;
import static P1.Mattel.Lectura_Txt;
import static P1.Mattel.cargar_data_default_txt;
import javax.swing.JOptionPane;
import P1.info;

/**
 *
 * @author DELL
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    public void validar_solo_operadores_operandos(java.awt.event.KeyEvent evento) {//Método para validar solo números
        if (!(evento.getKeyChar() >=48 || evento.getKeyChar()==8) || !(evento.getKeyChar() <=57 || evento.getKeyChar()==127 )) {
            evento.consume();
                JOptionPane.showMessageDialog(this, "Solo numeros.");
        }
    }
    
    public static boolean isNumeric(String str) {
        for (char c : str.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        jButton4 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cargar data default");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Set Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField1KeyTyped(evt);
            }
        });

        textField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField2KeyTyped(evt);
            }
        });

        textField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField3ActionPerformed(evt);
            }
        });
        textField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField3KeyTyped(evt);
            }
        });

        textField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField4KeyTyped(evt);
            }
        });

        textField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField5KeyTyped(evt);
            }
        });

        textField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField6KeyTyped(evt);
            }
        });

        jButton4.setText("Empezar Simulacion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        label1.setText("Productores de piernas");

        label2.setText("Cantidad de dias entre despachos");

        label3.setText("Productores de botones");

        label4.setText("Tiempo");

        label5.setText("Productores de cuerpo central");

        label6.setText("Productores de brazos");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        label7.setText("Ensambladores");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel1.setText("MAX");

        jLabel9.setText("MAX");

        jLabel10.setText("MAX");

        jLabel11.setText("MAX");

        jLabel12.setText("MAX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(textField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(84, 84, 84)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)))
                        .addGap(68, 68, 68)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(38, 38, 38)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("Set data");

        
        String p_piernas=this.textField1.getText();
        String p_brazos=this.textField2.getText();
        String p_cuerpoC=this.textField3.getText();
        String p_botones=this.textField4.getText();
        String ensambladores=this.textField5.getText();
        String tiempo=this.textField6.getText();
        String cant_d_entre_d=this.jTextField1.getText();
        String max_piernas=this.jTextField2.getText();
        String max_brazos=this.jTextField3.getText();
        String max_cuerpoC=this.jTextField4.getText();
        String max_botones=this.jTextField5.getText();
        String max_ensambladores=this.jTextField6.getText();
        if(
            textField1.getText().isBlank() || 
            textField2.getText().isBlank() || 
            textField3.getText().isBlank() ||
            textField4.getText().isBlank() ||
            textField5.getText().isBlank() ||
            jTextField1.getText().isBlank()||
            jTextField2.getText().isBlank()||
            jTextField3.getText().isBlank()||     
            jTextField4.getText().isBlank()||
            jTextField5.getText().isBlank()||
            jTextField6.getText().isBlank()
                ){
            
            JOptionPane.showMessageDialog(this, "Para setear la data debes rellenar todos los campos");
        }else{
            int max_prod_btn=4;
            int max_prod_brz=5;
            int max_prod_pier=4;
            int max_prod_cuerC=4;
            int max_ensmb=5;

            String defaultText="";
            String[] prob= {
                            "La empresa solo puede costear maximo 4 productores de botones\n",
                            "La empresa solo puede costear maximo 5 productores de brazos\n",
                            "La empresa solo puede costear maximo 4 productores de piernas\n",
                            "La empresa solo puede costear maximo 4 productores de cuerpo central\n",
                            "La empresa solo puede costrear maximo 5 ensambladores\n",
                            "La cantiadad de productores de piernas es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de productores de brazos es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de productores de cuerpo central es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de productores de botones es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de ensambladores es mayor a la cantidad maxima que estableciste\n",
                            "Las cantidades maximas de los campos no pueden ser menores o iguales a 0\nPor favor revise la informacion suministrada.\n"
                            
            };
//            if(Integer.parseInt(jTextField2.getText())> max_prod_pier){ defaultText+=prob[2];}
//            if(Integer.parseInt(jTextField3.getText())> max_prod_brz){ defaultText+=prob[1];}
//            if(Integer.parseInt(jTextField4.getText())> max_prod_cuerC){ defaultText+=prob[3];}
//            if(Integer.parseInt(jTextField5.getText())> max_prod_btn){ defaultText+=prob[0];}
//            if(Integer.parseInt(jTextField6.getText())> max_ensmb){ defaultText+=prob[4];}
            
            if(Integer.parseInt(jTextField2.getText())<= 0 || 
               Integer.parseInt(jTextField3.getText())<= 0 ||
               Integer.parseInt(jTextField4.getText())<= 0 ||
               Integer.parseInt(jTextField5.getText())<= 0 ||
               Integer.parseInt(jTextField6.getText())<= 0){ 
                
                    defaultText+=prob[10];
            
            }
            if(!defaultText.isBlank()){
                JOptionPane.showMessageDialog(this, defaultText);
            }else if(defaultText.isBlank()){
                if(Integer.parseInt(textField1.getText())> Integer.parseInt(jTextField2.getText())){ defaultText+=prob[5];}
                if(Integer.parseInt(textField2.getText())> Integer.parseInt(jTextField3.getText())){ defaultText+=prob[6];}
                if(Integer.parseInt(textField3.getText())> Integer.parseInt(jTextField4.getText())){ defaultText+=prob[7];}
                if(Integer.parseInt(textField4.getText())> Integer.parseInt(jTextField5.getText())){ defaultText+=prob[8];}
                if(Integer.parseInt(textField5.getText())> Integer.parseInt(jTextField6.getText())){ defaultText+=prob[9];}

                if(!defaultText.isBlank()){
                JOptionPane.showMessageDialog(this, defaultText);
            }else{
                Escritura_Txt(p_piernas,
                              p_brazos,
                              p_cuerpoC,
                              p_botones,
                              ensambladores,
                              tiempo,
                              cant_d_entre_d,
                              max_piernas,
                              max_brazos,
                              max_cuerpoC,
                              max_botones,
                              max_ensambladores);
        
            String data= Lectura_Txt();
            String [] info=data.split(",");
        
            this.textField1.setText(info[0]);
            this.textField2.setText(info[1]);
            this.textField3.setText(info[2]);
            this.textField4.setText(info[3]);
            this.textField5.setText(info[4]);
            this.textField6.setText(info[5]);
            this.jTextField1.setText(info[6]);
            this.jTextField2.setText(info[7]);
            this.jTextField3.setText(info[8]);
            this.jTextField4.setText(info[9]);
            this.jTextField5.setText(info[10]);
            this.jTextField6.setText(info[11]);
            }
            
        }
        
    }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.out.println("Cargar data default");
        cargar_data_default_txt();
        String data= Lectura_Txt();
        
        String [] info=data.split(",");
        
        this.textField1.setText(info[0]);
        this.textField2.setText(info[1]);
        this.textField3.setText(info[2]);
        this.textField4.setText(info[3]);
        this.textField5.setText(info[4]);
        this.textField6.setText(info[5]);
        this.jTextField1.setText(info[6]);
        this.jTextField2.setText(info[7]);
        this.jTextField3.setText(info[8]);
        this.jTextField4.setText(info[9]);
        this.jTextField5.setText(info[10]);
        this.jTextField6.setText(info[11]);

        String p_piernas=this.textField1.getText();
        String p_brazos=this.textField2.getText();
        String p_cuerpoC=this.textField3.getText();
        String p_botones=this.textField4.getText();
        String ensambladores=this.textField5.getText();
        String tiempo=this.textField6.getText();
        String cant_d_entre_d=this.jTextField1.getText();
        String max_piernas=this.jTextField2.getText();
        String max_brazos=this.jTextField3.getText();
        String max_cuerpoC=this.jTextField4.getText();
        String max_botones=this.jTextField5.getText();
        String max_ensambladores=this.jTextField6.getText();
        Escritura_Txt(p_piernas,
                              p_brazos,
                              p_cuerpoC,
                              p_botones,
                              ensambladores,
                              tiempo,
                              cant_d_entre_d,
                              max_piernas,
                              max_brazos,
                              max_cuerpoC,
                              max_botones,
                              max_ensambladores);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Cargar data del txt");
        String data= Lectura_Txt();
        System.out.println(data);
        if(data.isBlank() || data.replace("\n", "").length()==0){
            JOptionPane.showMessageDialog(this, "No es posible cargar data del txt");
        }else{
            

            String [] info=data.split(",");

            this.textField1.setText(info[0]);
            this.textField2.setText(info[1]);
            this.textField3.setText(info[2]);
            this.textField4.setText(info[3]);
            this.textField5.setText(info[4]);
            this.textField6.setText(info[5]);
            this.jTextField1.setText(info[6]);
            this.jTextField2.setText(info[7]);
            this.jTextField3.setText(info[8]);
            this.jTextField4.setText(info[9]);
            this.jTextField5.setText(info[10]);
            this.jTextField6.setText(info[11]);

            String p_piernas=this.textField1.getText();
            String p_brazos=this.textField2.getText();
            String p_cuerpoC=this.textField3.getText();
            String p_botones=this.textField4.getText();
            String ensambladores=this.textField5.getText();
            String tiempo=this.textField6.getText();
            String cant_d_entre_d=this.jTextField1.getText();
            String max_piernas=this.jTextField2.getText();
            String max_brazos=this.jTextField3.getText();
            String max_cuerpoC=this.jTextField4.getText();
            String max_botones=this.jTextField5.getText();
            String max_ensambladores=this.jTextField6.getText();
            Escritura_Txt(p_piernas,
                                  p_brazos,
                                  p_cuerpoC,
                                  p_botones,
                                  ensambladores,
                                  tiempo,
                                  cant_d_entre_d,
                                  max_piernas,
                                  max_brazos,
                                  max_cuerpoC,
                                  max_botones,
                                  max_ensambladores);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.out.println("Empezar simulacion");
        
        int max_prod_btn=4;
        int max_prod_brz=5;
        int max_prod_pier=4;
        int max_prod_cuerC=4;
        int max_ensmb=5;
        
        String defaultText="";
        String[] prob= {
                            "La empresa solo puede costear maximo 4 productores de botones\n",
                            "La empresa solo puede costear maximo 5 productores de brazos\n",
                            "La empresa solo puede costear maximo 4 productores de piernas\n",
                            "La empresa solo puede costear maximo 4 productores de cuerpo central\n",
                            "La empresa solo puede costrear maximo 5 ensambladores\n",
                            "La cantiadad de productores de piernas es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de productores de brazos es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de productores de cuerpo central es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de productores de botones es mayor a la cantidad maxima que estableciste\n",
                            "La cantiadad de ensambladores es mayor a la cantidad maxima que estableciste\n"
                            };
        
        if(
            textField1.getText().isBlank() || 
            textField2.getText().isBlank() || 
            textField3.getText().isBlank() ||
            textField4.getText().isBlank() ||
            textField5.getText().isBlank() ||
            jTextField1.getText().isBlank()||
            jTextField2.getText().isBlank()||
            jTextField3.getText().isBlank()||     
            jTextField4.getText().isBlank()||
            jTextField5.getText().isBlank()||
            jTextField6.getText().isBlank()
                                
                ){
            
            JOptionPane.showMessageDialog(this, "No se ha cargado correctamente la informacion necesario para empezar la simulacion.");
        }else{
//            if(Integer.parseInt(jTextField2.getText())> max_prod_pier){ defaultText+=prob[2];}
//            if(Integer.parseInt(jTextField3.getText())> max_prod_brz){ defaultText+=prob[1];}
//            if(Integer.parseInt(jTextField4.getText())> max_prod_cuerC){ defaultText+=prob[3];}
//            if(Integer.parseInt(jTextField5.getText())> max_prod_btn){ defaultText+=prob[0];}
//            if(Integer.parseInt(jTextField6.getText())> max_ensmb){ defaultText+=prob[4];}
            
            if(!defaultText.isBlank()){
                JOptionPane.showMessageDialog(this, defaultText);
            }else if(defaultText.isBlank()){
                    if(Integer.parseInt(textField1.getText())> Integer.parseInt(jTextField2.getText())){ defaultText+=prob[5];}
                    if(Integer.parseInt(textField2.getText())> Integer.parseInt(jTextField3.getText())){ defaultText+=prob[6];}
                    if(Integer.parseInt(textField3.getText())> Integer.parseInt(jTextField4.getText())){ defaultText+=prob[7];}
                    if(Integer.parseInt(textField4.getText())> Integer.parseInt(jTextField5.getText())){ defaultText+=prob[8];}
                    if(Integer.parseInt(textField5.getText())> Integer.parseInt(jTextField6.getText())){ defaultText+=prob[9];}

                    if(!defaultText.isBlank()){
                    JOptionPane.showMessageDialog(this, defaultText);

                }else{
                    
                    Mattel.capacidad_productores[2]=Integer.parseInt(jTextField2.getText());
                    Mattel.capacidad_productores[1]=Integer.parseInt(jTextField3.getText());
                    Mattel.capacidad_productores[3]=Integer.parseInt(jTextField4.getText());
                    Mattel.capacidad_productores[0]=Integer.parseInt(jTextField5.getText());
                    Mattel.capacidad_ensambladores=Integer.parseInt(jTextField6.getText());
                    
                    this.setVisible(false);
                    info v = new info();
                    v.setVisible(true);
                }
            
            }
            
        }
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField3ActionPerformed

    private void textField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_textField1KeyTyped

    private void textField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField2KeyTyped
        validar_solo_operadores_operandos(evt);        
    }//GEN-LAST:event_textField2KeyTyped

    private void textField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField3KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_textField3KeyTyped

    private void textField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField4KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_textField4KeyTyped

    private void textField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField5KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_textField5KeyTyped

    private void textField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField6KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_textField6KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        validar_solo_operadores_operandos(evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
